server:
  port: 8083 # 8083 or 8084
spring:
  main:
    allow-circular-references: true
dubbo:
  registry:
    protocol: dubbo
    address: nacos://127.0.0.1:8848
    use-as-config-center: true
    use-as-metadata-center: true
  application:
    name: tcc-dubbo-provider # tcc-dubbo-provider or tcc-dubbo-consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: -1 # 端口动态自增

seata:
  enabled: true
  application-id: dubbo-tcc-sample
  tx-service-group: my_test_tx_group
  #enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      dataId: "seataServer.properties"
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: seata-server
      group: SEATA_GROUP
      application: seata-server
      cluster: default