server:
  port: 8094

spring:
  aop: #使用CGLIB来实现AOP的时候
    proxy-target-class: true
  application:
    name: shardingsphere-seata-dubbo-consumer

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    group: SEATA_GROUP
    username: nacos
    password: nacos
  application:
    name: shardingsphere-seata-dubbo-consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: 10001

seata:
  enabled: true
  #enable-auto-data-source-proxy: false
  #use-jdk-proxy: true
  application-id: shardingsphere-seata-consumer
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: seata-server
      group: SEATA_GROUP
      dataId: "seataServer.properties"
      #username: "nacos"
      #password: "nacos"
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: seata-server
      group: SEATA_GROUP
      application: seata-server
      cluster: default

#endpoint http://localhost:8080/actuator/nacos-config
#health http://localhost:8080/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: '*'