spring:
  application:
    name: test-consumer
  mvc:
    servlet:
      load-on-startup: 1
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 28888
  max-http-header-size: 8192
  address: 0.0.0.0
  tomcat:
    max-http-post-size: 104857600

dubbo:
  registry:
    id: my-registry
    address: nacos://127.0.0.1:8848
    group: SEATA_GROUP
    username: nacos
    password: nacos
  application:
    name: test-consumer
    qos-enable: false

seata:
  enabled: true
  application-id: dubbo-md-mp-consumer
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      dataId: seataServer.properties
      username: nacos
      password: nacos
  registry:
    type: zk
    zk:
      cluster: default
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password: