server:
  port: 8095

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    group: SEATA_GROUP
    username: nacos
    password: nacos
  application:
    name: shardingsphere-seata-nacos-dubbo-provider-order
    qos-enable: false
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: io.seata.samples.shardingsphere.modules.service

#endpoint http://localhost:8080/actuator/nacos-config
#health http://localhost:8080/actuator/health
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: shardingsphere-seata-nacos-dubbo-provider-order
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:33306/ds_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:33306/ds_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: user_id
            sharding-algorithm-name: database-inline
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 2}
          t-order-inline:
            type: INLINE
            props:
              algorithm-expression: t_order_$->{order_id % 2}
          t-order-item-inline:
            type: INLINE
            props:
              algorithm-expression: t_order_item_$->{order_id % 2}

        tables:
          t_order:
            actual-data-nodes: ds$->{0..1}.t_order_$->{0..1}
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: t-order-inline
            key-generate-strategy:
              column: order_id
              key-generator-name: snowflake

          t_order_item:
            actual-data-nodes: ds$->{0..1}.t_order_item_$->{0..1}
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: t-order-item-inline
            key-generate-strategy:
              column: order_item_id
              key-generator-name: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE

seata:
  enabled: true
  # 必须配置为false，datasource由shardingsphere而不是seata接管：ShardingSphereDataSource，
  # 进而初始化 SeataATShardingSphereTransactionManager，负责与seata server交互
  enable-auto-data-source-proxy: false
  use-jdk-proxy: true
  application-id: shardingsphere-seata-order
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      dataId: seataServer.properties
      username: nacos
      password: nacos
  registry:
    type: zk
    zk:
      cluster: default
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:

#mybatis:
#  mapper-locations: classpath:/mapper/**/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.company.spring.boot.shardingsphere.seata.modules.entity  #这里是实体类的位置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false

mybatis-plus:
  #  datasource: dataSource
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: io.seata.samples.shardingsphere.modules.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID", 4:"该类型为未设置主键类型", 5:"字符串全局唯一ID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型