server:
  port: 8087

dubbo:
  application:
    name: saga-dubbo-consumer
    qos-enable: false
  registry:
    protocol: dubbo
    address: nacos://127.0.0.1:8848
    group: SEATA_GROUP
    register: false # 不提供服务，只消费服务
    use-as-config-center: true
    use-as-metadata-center: true
  protocol:
    name: dubbo
    port: 20881 # -1: 端口自增
    threads: 200
    queues: 100
    threadpool: cached
  provider:
    retries: 3
    threadpool: cached
    threads: 200
    connections: 100

seata:
  enabled: true
  application-id: dubbo-saga-sample
  tx-service-group: default_tx_group
  enable-auto-data-source-proxy: false  # saga设置为false
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: seata-server
      group: SEATA_GROUP
      dataId: "seataServer.properties"
      #username: "nacos"
      #password: "nacos"
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: seata-server
      group: SEATA_GROUP
      application: seata-server
      cluster: default