server:
  port: 8086
spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_local_saga?useSSL=false&serverTimezone=UTC
    username: mysql
    password: mysql

seata:
  enabled: true
  application-id: local-saga-sample
  tx-service-group: default_tx_group
  #enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: seata-server
      group: SEATA_GROUP
      dataId: "seataServer.properties"
      #username: "nacos"
      #password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: seata-server
      cluster: default
